name: process
on:
  push:
    paths:
    - 'in/**'
jobs:
  wrap:
    name: Wrapping a text in the template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash wrap.sh
