name: process
on:
  push:
    paths:
    - 'in/**'
jobs:
  wrap:
    name: Wrapping a text in the template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash wrap.sh
      - run: git config user.email "q21@bk.ru"
      - run: git config user.name "chang-zhao"
      - run: git commit . -m "Wrapping"
      - run: git push origin main
