name: process
on:
  push:
    paths:
    - 'in/**'
jobs:
  wrap:
    name: Wrapping a text in the template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - run: cat out/head.html > pack/**
#      - run: cat in/** >> pack/**
#      - run: cat out/foot.html >> pack/**
